version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    parallelism: 3
    working_directory: ~/frontend/src
    steps:
      - checkout
          path: frontend

      - restore_cache:
          keys:
            - src-{{ checksum "package.json" }}
            - src-

      - run:
          name: Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: src-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test --collectCoverage=true
      - store_artifacts:
          path: coverage

      - codecov/upload:
          file: coverage/*.json
